name: 03 (Dispatch) Apply Integration To Env

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Which Environment to Deploy to?'
        required: true
        type: choice
        options: 
        - qa
        - stg
        - prd

env:
  TF_VERSION: 1.0.0
  TG_VERSION: 0.38.5
  CI: true

jobs:
  deploy-to-env:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git checkout
        id: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.1
        with:
          terragrunt_version: ${{ env.TG_VERSION }}

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false 

      - name: Setup SSH Keys and known_hosts
        #  Copied from https://github.com/maddox/actions/blob/master/ssh/entrypoint.sh
        run: |
          SSH_PATH="$HOME/.ssh"
          mkdir -p "$SSH_PATH"
          touch "$SSH_PATH/known_hosts"
          echo "${{secrets.ID_RSA}}" > "$SSH_PATH/id_rsa"
          chmod 700 "$SSH_PATH"
          ssh-keyscan github.com >> "$SSH_PATH/known_hosts"
          chmod 600 "$SSH_PATH/known_hosts"
          chmod 600 "$SSH_PATH/id_rsa"
          eval $(ssh-agent)
          ssh-add "$SSH_PATH/id_rsa"

      - name: AWS Credentials
        id: aws-credentials
        run: |
          mkdir -p ~/.aws
          touch ~/.aws/credentials
          echo "${{secrets.AWS_CREDENTIALS_FILE}}" > ~/.aws/credentials    

      - name: Terragrunt ${{ github.event.inputs.environment }} Base Apply
        id: apply-base
        working-directory: environments/${{ github.event.inputs.environment }}/cl/base
        run: |
          terragrunt init
          terragrunt plan -no-color
          terragrunt apply -no-color -auto-approve
      
      - name: Terragrunt ${{ github.event.inputs.environment }} Actions Apply
        id: apply-actions
        working-directory: environments/${{ github.event.inputs.environment }}/cl/actions
        run: |
          terragrunt init
          terragrunt plan -no-color
          terragrunt apply -no-color -auto-approve
