name: Unit Tests on PR

on:
  pull_request:
    types: [opened]
    branches: [integration]
  issue_comment:
    types: [created]

env:
  CI: true

jobs:
  test:
    if: |
      (startsWith(github.event.comment.body, '/test'))
      || (github.event_name == 'pull_request' && github.event.action == 'opened')
    runs-on: ubuntu-18.04
    timeout-minutes: 30
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: cd js && yarn

      - name: Run Eslint
        run: cd js && yarn eslint

      - name: Run Unit Test
        run: cd js && yarn test
