import { IStrapiSweepstake } from '@/types/strapi';

const MOCK_IMAGE = {
    data: {
        id: 5,
        attributes: {
            name: 'HeroImage.webp',
            alternativeText: 'HeroImage.webp',
            caption: 'HeroImage.webp',
            width: 812,
            height: 457,
            formats: {
                small: {
                    ext: '.webp',
                    url: 'https://assets.stg.omazedev.com/coreloop/media-library/small_Hero_Image_edc99b347b.webp',
                    hash: 'small_Hero_Image_edc99b347b',
                    mime: 'image/webp',
                    name: 'small_HeroImage.webp',
                    path: 'media-library/',
                    size: 23.92,
                    width: 500,
                    height: 281,
                },
                thumbnail: {
                    ext: '.webp',
                    url: 'https://assets.stg.omazedev.com/coreloop/media-library/thumbnail_Hero_Image_edc99b347b.webp',
                    hash: 'thumbnail_Hero_Image_edc99b347b',
                    mime: 'image/webp',
                    name: 'thumbnail_HeroImage.webp',
                    path: 'media-library/',
                    size: 6.97,
                    width: 245,
                    height: 138,
                },
            },
            hash: 'Hero_Image_edc99b347b',
            ext: '.webp',
            mime: 'image/webp',
            size: 52.98,
            url: 'https://assets.stg.omazedev.com/coreloop/media-library/Hero_Image_edc99b347b.webp',
            previewUrl:
                'https://assets.stg.omazedev.com/coreloop/media-library/Hero_Image_edc99b347b-thumb.webp',
            provider: '@iamsamwen/provider-upload-aws-s3-plus',
            provider_metadata: null,
            createdAt: '2022-08-11T20:05:50.268Z',
            updatedAt: '2022-08-11T20:05:50.268Z',
        },
    },
};

const MOCK_HERO_IMAGE = {
    data: [
        {
            id: 1,
            attributes: {
                name: 'HeroImage1.jpg',
                alternativeText: 'HeroImage1.jpg',
                caption: 'HeroImage1.jpg',
                width: 1000,
                height: 1000,
                formats: {
                    small: {
                        ext: '.jpg',
                        url: 'https://assets.qa.omazedev.com/coreloop/media-library/small_Hero_Image_2c65857927.jpg',
                        hash: 'small_Hero_Image_2c65857927',
                        mime: 'image/jpeg',
                        name: 'small_HeroImage.jpg',
                        path: 'media-library/',
                        size: 63.95,
                        width: 500,
                        height: 500,
                    },
                    medium: {
                        ext: '.jpg',
                        url: 'https://assets.qa.omazedev.com/coreloop/media-library/medium_Hero_Image_2c65857927.jpg',
                        hash: 'medium_Hero_Image_2c65857927',
                        mime: 'image/jpeg',
                        name: 'medium_HeroImage.jpg',
                        path: 'media-library/',
                        size: 140.62,
                        width: 750,
                        height: 750,
                    },
                    thumbnail: {
                        ext: '.jpg',
                        url: 'https://assets.qa.omazedev.com/coreloop/media-library/thumbnail_Hero_Image_2c65857927.jpg',
                        hash: 'thumbnail_Hero_Image_2c65857927',
                        mime: 'image/jpeg',
                        name: 'thumbnail_HeroImage.jpg',
                        path: 'media-library/',
                        size: 6.67,
                        width: 156,
                        height: 156,
                    },
                },
                hash: 'Hero_Image_2c65857927',
                ext: '.jpg',
                mime: 'image/jpeg',
                size: 197.25,
                url: 'https://assets.qa.omazedev.com/coreloop/media-library/Hero_Image_2c65857927.jpg',
                previewUrl:
                    'https://assets.qa.omazedev.com/coreloop/media-library/Hero_Image_2c65857927-thumb.jpg',
                provider: '@iamsamwen/provider-upload-aws-s3-plus',
                provider_metadata: null,
                createdAt: '2022-09-08T23:14:06.206Z',
                updatedAt: '2022-09-08T23:14:06.206Z',
            },
        },
        {
            id: 2,
            attributes: {
                name: 'HeroImage2.jpg',
                alternativeText: 'HeroImage2.jpg',
                caption: 'HeroImage2.jpg',
                width: 1200,
                height: 1200,
                formats: {
                    large: {
                        ext: '.jpg',
                        url: 'https://assets.qa.omazedev.com/coreloop/media-library/large_Prize_Details_Image3_b0d1a4c774.jpg',
                        hash: 'large_Prize_Details_Image3_b0d1a4c774',
                        mime: 'image/jpeg',
                        name: 'large_PrizeDetailsImage3.jpg',
                        path: 'media-library/',
                        size: 132.63,
                        width: 1000,
                        height: 1000,
                    },
                    small: {
                        ext: '.jpg',
                        url: 'https://assets.qa.omazedev.com/coreloop/media-library/small_Prize_Details_Image3_b0d1a4c774.jpg',
                        hash: 'small_Prize_Details_Image3_b0d1a4c774',
                        mime: 'image/jpeg',
                        name: 'small_PrizeDetailsImage3.jpg',
                        path: 'media-library/',
                        size: 47.43,
                        width: 500,
                        height: 500,
                    },
                    medium: {
                        ext: '.jpg',
                        url: 'https://assets.qa.omazedev.com/coreloop/media-library/medium_Prize_Details_Image3_b0d1a4c774.jpg',
                        hash: 'medium_Prize_Details_Image3_b0d1a4c774',
                        mime: 'image/jpeg',
                        name: 'medium_PrizeDetailsImage3.jpg',
                        path: 'media-library/',
                        size: 87.32,
                        width: 750,
                        height: 750,
                    },
                    thumbnail: {
                        ext: '.jpg',
                        url: 'https://assets.qa.omazedev.com/coreloop/media-library/thumbnail_Prize_Details_Image3_b0d1a4c774.jpg',
                        hash: 'thumbnail_Prize_Details_Image3_b0d1a4c774',
                        mime: 'image/jpeg',
                        name: 'thumbnail_PrizeDetailsImage3.jpg',
                        path: 'media-library/',
                        size: 7.61,
                        width: 156,
                        height: 156,
                    },
                },
                hash: 'Prize_Details_Image3_b0d1a4c774',
                ext: '.jpg',
                mime: 'image/jpeg',
                size: 153.8,
                url: 'https://assets.qa.omazedev.com/coreloop/media-library/Prize_Details_Image3_b0d1a4c774.jpg',
                previewUrl:
                    'https://assets.qa.omazedev.com/coreloop/media-library/Prize_Details_Image3_b0d1a4c774-thumb.jpg',
                provider: '@iamsamwen/provider-upload-aws-s3-plus',
                provider_metadata: null,
                createdAt: '2022-09-08T23:14:06.612Z',
                updatedAt: '2022-09-08T23:14:06.612Z',
            },
        },
        {
            id: 3,
            attributes: {
                name: 'HeroImage3.jpg',
                alternativeText: 'HeroImage3.jpg',
                caption: 'HeroImage3.jpg',
                width: 1976,
                height: 1967,
                formats: {
                    large: {
                        ext: '.jpg',
                        url: 'https://assets.qa.omazedev.com/coreloop/media-library/large_Prize_Details_Image2_08f94ee824.jpg',
                        hash: 'large_Prize_Details_Image2_08f94ee824',
                        mime: 'image/jpeg',
                        name: 'large_PrizeDetailsImage2.jpg',
                        path: 'media-library/',
                        size: 135.59,
                        width: 1000,
                        height: 995,
                    },
                    small: {
                        ext: '.jpg',
                        url: 'https://assets.qa.omazedev.com/coreloop/media-library/small_Prize_Details_Image2_08f94ee824.jpg',
                        hash: 'small_Prize_Details_Image2_08f94ee824',
                        mime: 'image/jpeg',
                        name: 'small_PrizeDetailsImage2.jpg',
                        path: 'media-library/',
                        size: 40.81,
                        width: 500,
                        height: 497,
                    },
                    medium: {
                        ext: '.jpg',
                        url: 'https://assets.qa.omazedev.com/coreloop/media-library/medium_Prize_Details_Image2_08f94ee824.jpg',
                        hash: 'medium_Prize_Details_Image2_08f94ee824',
                        mime: 'image/jpeg',
                        name: 'medium_PrizeDetailsImage2.jpg',
                        path: 'media-library/',
                        size: 80.33,
                        width: 750,
                        height: 747,
                    },
                    thumbnail: {
                        ext: '.jpg',
                        url: 'https://assets.qa.omazedev.com/coreloop/media-library/thumbnail_Prize_Details_Image2_08f94ee824.jpg',
                        hash: 'thumbnail_Prize_Details_Image2_08f94ee824',
                        mime: 'image/jpeg',
                        name: 'thumbnail_PrizeDetailsImage2.jpg',
                        path: 'media-library/',
                        size: 6.86,
                        width: 157,
                        height: 156,
                    },
                },
                hash: 'Prize_Details_Image2_08f94ee824',
                ext: '.jpg',
                mime: 'image/jpeg',
                size: 361.52,
                url: 'https://assets.qa.omazedev.com/coreloop/media-library/Prize_Details_Image2_08f94ee824.jpg',
                previewUrl:
                    'https://assets.qa.omazedev.com/coreloop/media-library/Prize_Details_Image2_08f94ee824-thumb.jpg',
                provider: '@iamsamwen/provider-upload-aws-s3-plus',
                provider_metadata: null,
                createdAt: '2022-09-08T23:14:06.696Z',
                updatedAt: '2022-09-08T23:14:06.696Z',
            },
        },
    ],
};

export const MOCK_STRAPI_SWEEPSTAKE: IStrapiSweepstake = {
    id: 1,
    attributes: {
        slug: 'mobile-maldives-test',
        heroImage: MOCK_HERO_IMAGE,
        heroImageMobile: MOCK_HERO_IMAGE,
        details: {
            id: 112,
            detailsSupport: 'Support Make A Wish and',
            detailsTitle:
                'Win a Dream Vacation in an Overwater Villa in the Maldives',
            detailsBodyText:
                'Win a 5-day vacation at The St. Regis Vommuli Resort in the Dhaalu Atoll (flights included)\\nRelax in a breathtaking overwater villa with a private deck and plunge pool overlooking coral atolls and sparkling turquoise lagoons\\nScore $5000 to spend on tailored wellness experiences, a glass-bottom kayak tour, decadent dining, and more',
            detailsLegalText:
                'Your safety and peace of mind are our top priority, so we’ll make sure this trip is scheduled when it’s safe. You’ll have until July 29, 2024 to book travel.',
        },
        prizeDetailsTitle:
            'What will you get up to on your Indian Ocean adventure?',
        prizeDetails: [
            {
                id: 1,
                prizeDetailsSubtitle: 'Ready to lounge in 5-star paradise?',
                prizeDetailsBody:
                    'Seek no further than this trip for two in the Maldives! The St. Regis Vommuli Resort, on the private island of Dhaalu Atoll, is at your service.',
                prizeDetailsImage: MOCK_IMAGE,
            },
            {
                id: 2,
                prizeDetailsSubtitle: 'A paradise at sea...',
                prizeDetailsBody:
                    'With a whole feast of ways to relax, the hardest choice will be whether to take a plunge in the turquoise lagoon or sway in a hammock in your overwater villa.',
                prizeDetailsImage: MOCK_IMAGE,
            },
            {
                id: 3,
                prizeDetailsSubtitle: 'Seize the day',
                prizeDetailsBody:
                    'The activities are endless... Plus, live your most luxurious life with an extra $5K stipend on us! ',
                prizeDetailsImage: MOCK_IMAGE,
            },
        ],
        charityInfo: {
            id: 113,
            charityDetailsTitle: 'Make A Wish',
            charityDetailsBody:
                'Enormous Differences\\n\\nMake-A-Wish creates life-changing wishes for children with critical illnesses.\\n\\nHelp Restore Hope\\n\\nNot only can these wishes help kids build the physical and emotional strength they need to fight a critical illness, they also restore hope for families, volunteers, medical teams and entire communities.\\n\\nAlways More To Do\\n\\nRight now, for every wish granted, there are three more that need financial support. ',
            charityDetailsLegalText:
                'This experience raises funds for Charities Aid Foundation America (“CAF America”), a US-registered, 501(c)(3) public charity. 100% of donations for this experience go to CAF America, which will then grant the donations, minus the experience fees and costs, to Make-A-Wish Foundation of America (the “Designated Grantee”). For more information, see the “Fundraising Transparency” section below.',
            charityDetailsCharityLogo: MOCK_IMAGE,
            charityDetailsImage: MOCK_IMAGE,
        },
        subprizes: [
            {
                id: 1,
                apiId: '54e3783e-b16d-4af4-90c4-44d55aaefb8e',
                slug: 'test-subprize-slug',
                imageAlt: 'test subprize image alt',
                title: 'Porsche',
                winnerName: 'test subprize winner name',
                winnerLocation: 'test subprize winner location',
                image: {
                    data: {
                        id: 5,
                        attributes: {
                            name: 'HeroImage.webp',
                            alternativeText: 'HeroImage.webp',
                            caption: 'HeroImage.webp',
                            width: 812,
                            height: 457,
                            formats: {
                                small: {
                                    ext: '.webp',
                                    url: 'https://assets.stg.omazedev.com/coreloop/media-library/small_Hero_Image_edc99b347b.webp',
                                    hash: 'small_Hero_Image_edc99b347b',
                                    mime: 'image/webp',
                                    name: 'small_HeroImage.webp',
                                    path: 'media-library/',
                                    size: 23.92,
                                    width: 500,
                                    height: 281,
                                },
                                thumbnail: {
                                    ext: '.webp',
                                    url: 'https://assets.stg.omazedev.com/coreloop/media-library/thumbnail_Hero_Image_edc99b347b.webp',
                                    hash: 'thumbnail_Hero_Image_edc99b347b',
                                    mime: 'image/webp',
                                    name: 'thumbnail_HeroImage.webp',
                                    path: 'media-library/',
                                    size: 6.97,
                                    width: 245,
                                    height: 138,
                                },
                            },
                            hash: 'Hero_Image_edc99b347b',
                            ext: '.webp',
                            mime: 'image/webp',
                            size: 52.98,
                            url: 'https://assets.stg.omazedev.com/coreloop/media-library/Hero_Image_edc99b347b.webp',
                            previewUrl: null,
                            provider: '@iamsamwen/provider-upload-aws-s3-plus',
                            provider_metadata: null,
                            createdAt: '2022-08-11T20:05:50.268Z',
                            updatedAt: '2022-08-11T20:05:50.268Z',
                        },
                    },
                },
            },
            {
                id: 2,
                apiId: 'c01eed35-6dd5-4e82-a3c8-380b50b9151d',
                slug: 'test-subprize-slug',
                imageAlt: 'test subprize image alt',
                title: 'Toyota Sienna Hybrid',
                winnerName: 'test subprize winner name',
                winnerLocation: 'test subprize winner location',
                image: {
                    data: {
                        id: 5,
                        attributes: {
                            name: 'HeroImage.webp',
                            alternativeText: 'HeroImage.webp',
                            caption: 'HeroImage.webp',
                            width: 812,
                            height: 457,
                            formats: {
                                small: {
                                    ext: '.webp',
                                    url: 'https://assets.stg.omazedev.com/coreloop/media-library/small_Hero_Image_edc99b347b.webp',
                                    hash: 'small_Hero_Image_edc99b347b',
                                    mime: 'image/webp',
                                    name: 'small_HeroImage.webp',
                                    path: 'media-library/',
                                    size: 23.92,
                                    width: 500,
                                    height: 281,
                                },
                                thumbnail: {
                                    ext: '.webp',
                                    url: 'https://assets.stg.omazedev.com/coreloop/media-library/thumbnail_Hero_Image_edc99b347b.webp',
                                    hash: 'thumbnail_Hero_Image_edc99b347b',
                                    mime: 'image/webp',
                                    name: 'thumbnail_HeroImage.webp',
                                    path: 'media-library/',
                                    size: 6.97,
                                    width: 245,
                                    height: 138,
                                },
                            },
                            hash: 'Hero_Image_edc99b347b',
                            ext: '.webp',
                            mime: 'image/webp',
                            size: 52.98,
                            url: 'https://assets.stg.omazedev.com/coreloop/media-library/Hero_Image_edc99b347b.webp',
                            previewUrl: null,
                            provider: '@iamsamwen/provider-upload-aws-s3-plus',
                            provider_metadata: null,
                            createdAt: '2022-08-11T20:05:50.268Z',
                            updatedAt: '2022-08-11T20:05:50.268Z',
                        },
                    },
                },
            },
        ],
        winnerPendingTitle:
            'Thanks to everyone who entered to win a Dream Vacation in an Overwater Villa in the Maldives',
        winnerAnnounceTitle:
            'Meet the winner of a Dream Vacation in an Overwater Villa in the Maldives',
        winnerInfo: {
            id: 12333,
            winnerName: 'Juan Perez',
            winnerLocation: 'Los Angeles, CA',
            winnerImage: MOCK_IMAGE,
            winnerImageAlt: 'Winners smiling with cash',
            winnerYoutubeLink: '',
        },
        donationVariantsTitle:
            'Support Make A Wish today and enter for your chance to win!',
        rules: 'NO PURCHASE, PAYMENT, OR DONATION OF ANY KIND IS NECESSARY TO ENTER OR WIN. A PURCHASE, PAYMENT, OR DONATION WILL NOT INCREASE THE CHANCES OF WINNING. Capitalized terms used and not defined below have the respective meanings assigned to them in the Official Rules, available here.\\n\\n1.             <ul>Winner(s):\\n\\n<li>One (1) grand prize winner (the “Winner”) and one (1) guest (“Guest”)</li>\\n\\n2.              Sponsor:\\n\\n<li>Omaze, Inc. (referred to herein as “Omaze” or “Sponsor”)</li>\\n\\n3              Designated Grantee:\\n\\nMake-A-Wish Foundation of America  (Federal Tax ID # 86-0481941) (“Designated Grantee”).\\n\\nThis Experience is part of a fundraising campaign for Charities Aid Foundation America (“CAF America”), which is a globally recognized United States 501(c)(3) public charity. 100% of donations raised in this Experience go to CAF America, who will then grant the donations, minus experience fees and costs, to the Designated Grantee. For more information, inc`luding how much goes to the Designated Grantee(s), the expected timeframes in which the Designated Grantee(s) will receive the grants, and the rare instances when CAF America may reassign donations to another nonprofit, see the “Fundraising Transparency” section, below.\\n\\nAll Designated Grantees are pre-validated by CAF America to confirm they meet CAF America’s applicable eligibility requirements to receive grants. So long as the identified Designated Grantee remains eligible to receive grants from CAF America, CAF America will distribute grants to Designated Grantee out of the donations raised in this Experience.\\n\\n4.              Deadline to Enter:\\n\\nThis Experience begins May 30, 2022 at 12:00 a.m., Pacific Time, and ends July 29, 2022 at 11:59 p.m., Pacific Time (the “Entry Period”). Sponsor is the official timekeeper.\\n\\n5.              Entry Limit:\\n\\nThe maximum number of entries for any one person into this Experience (the “Entry Limit”) is six thousand (6,000), regardless of the method of entry.\\n\\n6.              Potential Winner Notification: \\n\\nA random drawing will be conducted on or after close of Entry Period. Winner will be drawn from among all valid entries received by Sponsor during the Entry Period. Potential Winner will be notified, on or after the close of Entry Period and must timely respond in accordance with the terms and deadlines stated in the Official Rules. \\n\\nOdds of winning depend on the number of eligible entries received during the Entry Period.\\n\\n7.              Prize Provider(s):\\n\\nOmaze and Quintessentially Travel Ltd. (“Prize Provider”).\\n\\n8.              Prize Details:\\n\\n(a)        The Grand Prize. Winner will receive a five (5) day, four (4) night stay for two (2) in a one-bedroom overwater villa at The St. Regis Maldives Vommuli Resort and a $5,000.00 (USD) stipend; round-trip flights and airport/hotel ground transfers in Maldives are included for Winner and Guest (the “Grand Prize”). The Grand Prize is strictly limited to those elements described in this Section 8. Any Grand Prize elements not specifically described in this Section 8 may be determined by Sponsor in its sole and absolute discretion. Sponsor may, in its sole and absolute discretion, present Winner with one or more Grand Prize options, from which Winner may choose one. However, Winner is not guaranteed or entitled to have the ability to request or demand any Prize elements that are not specifically stated in this Section 8.\\n\\n(i)        Approximate Retail Value (“ARV”): $25,000.00 (USD)\\n\\n(ii)       Anticipated Prize Fulfillment Date: TBD by Prize Provider in its sole and absolute discretion; provided, however, that travel must be booked by July 29, 2024. Winner will be requested to provide three (3) separate dates of preferred travel and Prize Provider will work towards fulfilling at least one (1) of those dates. Additionally, a minimum of six (6) weeks lead time prior to the preferred departure date is required for booking, and Winner and Guest passports must be valid for travel with a minimum of six (6) months of the date of departure. The holidays are subject to availability and blackout dates will apply. Blackout dates include peak Christmas, Easter and summer holidays (July 25 to August 15, annually). Once the package is booked it is non-changeable and non-refundable.\\n\\n(iii)      Prize Fulfillment Location: Maldives\\n\\n(iv)      Any Taxes or Fees Covered: None\\n\\n(b)        Cash Alternative. If Winner does not wish to take delivery of the Grand Prize, does not wish to accept one of the Grand Prize options presented by Sponsor (as applicable), or Sponsor determines that it cannot timely deliver the Grand Prize to Winner, for any reason, including without limitation due to legal restrictions, a force majeure event, failure of construction, or any other reason, the Winner may elect to take a cash alternative of $18,750.00 (USD) (the “Cash Alternative”). No additional prizes or compensation of any kind will be provided if the Cash Alternative is awarded.\\n\\nWinner must advise Sponsor in writing on or before deadline provided in writing from Sponsor, as to Winner’s election. If Winner does not timely notify the Sponsor in writing that Winner is electing to accept the Grand Prize, then Winner shall forfeit the opportunity to elect the Grand Prize, and Winner will automatically receive the Cash Alternative and not the Grand Prize. Winner’s decision between accepting either the Grand Prize or Cash Alternative cannot be changed by Winner for any reason.\\n\\nSponsor reserves the right to require Winner to take the Cash Alternative and remove the option of the Grand Prize if the Winner does not wish to accept one of the Grand Prize options presented by Sponsor (as applicable), or the Grand Prize cannot be fully awarded or otherwise delivered to Winner on or before the Anticipated Prize Fulfillment Date(s) stated above, for any reason, including without limitation due to a force majeure event, legal restrictions, supply chain disruptions, Prize supplier cancellation or delays, or failure of construction.\\n\\nExcept as explicitly stated, all Prizes are awarded as is, without any representations or warranties, and cannot be transferred, sold, substituted, or redeemed for cash by Winner. Unless noted in the Prize details in this Section 8, Winner is solely responsible for all taxes, costs, and fees associated with Prize receipt, ownership, and/or use.  In order to accept the Grand Prize, Winner and Guest must accurately complete and timely return all documentation required by Sponsor and/or the Prize Provider. \\n\\nAll third-party names and trademarks are the property of their respective owners. \\n\\n9.              Eligibility and Restrictions:\\n\\nThis is a Grand-Prize Experience (as defined in Section 5 of the Official Rules). Notwithstanding anything in the Official Rules to the contrary, including Section 4(A)(i) of the Official Rules, an individual who has won the grand prize in any Grand-Prize Experience (as defined in Section 5(A) of the Official Rules) at any time is eligible to win this Experience.  Individuals may not win more than one prize within a Secondary Promotion (as defined in Section 5(B) of the Official Rules) in connection with this Experience.\\n\\nAge to enter: You must be at least 18 years old to enter.  Guest must be at least 18 years old, provided, however, that Sponsor may, in its sole and absolute discretion, allow for Guest to be younger than 18 years old if (i) the Winner is the parent/legal guardian of the Guest, or (ii) the parent/legal guardian of the Guest provides written consent. Notwithstanding the foregoing, no individual younger than 5 years old may be a guest.\\n\\nProhibited Persons. In addition to those prohibited persons identified in Section 4(A) of the Official Rules, any employees, officers, and/or directors of the Designated Grantee(s) of this Experience are not eligible to enter or win this Experience.\\n\\nHealth and Safety: Sponsor and/or Prize Provider may require that Winner, and any Guest(s), (i) attest to having received certain vaccinations, including, without limitation, a COVID-19 vaccination, and provide proof of the same (in a format determined by Sponsor and/or Prize Provider in its sole discretion), and/or (ii) provide proof of a negative COVID-19 test (testing and proof of results in a format determined by Sponsor and/or Prize Provider in its sole discretion) in order to accept the Grand Prize. In the event a Winner, and any Guest(s), are unable to produce proof of vaccination and/or a negative COVID-19 test reasonably satisfactory to Sponsor and/or Prize Provider, Sponsor reserves the right to require that Winner take the Cash Alternative (if provided) or substitute an alternate Prize of equal or greater value in its sole discretion.\\n\\nIn addition to all of the other requirements stated in these Experience Rules and the Official Rules, if the Potential Winner is a Canadian resident, (s)he must correctly answer a mathematical skill-testing question to be eligible to be confirmed the Winner.\\n\\nEntry is subject to all applicable international, federal, state, and local laws and regulations and is void where prohibited. See the Official Rules for more details. In certain jurisdictions, local rules and laws may restrict or prohibit the award of certain prizes or impose additional restrictions on participation.\\n\\n10.           Winner Confirmation & Verification:  \\n\\nPotential Winners are subject to confirmation and verification by Sponsor per the terms and restrictions stated in the Official Rules. As part of the Winner confirmation and verification process Sponsor may conduct background check(s) on a Potential Winner (and any Guests of Potential Winner) except where legally prohibited. Background checks may occur without any additional notice to Potential Winner and/or prior to awarding the Prize(s), as may be permitted by law. Participation in an Experience constitutes Participant’s authorization to such background checks, without Sponsor providing additional prior notice or seeking additional authorizations or consents from Potential Winner.\\n\\n*        *        *\\n\\nCombo Promotion Terms - May 30 - June 3, 2022\\n\\nThe Maldives x Bora Bora promotion starts May 30, 2022 at 9:00 a.m., Pacific Time, and ends June 3, 2022 at 11:59 p.m., Pacific Time. This promotion is valid for the Maldives and Bora Bora Experiences only. When you enter one of these Experiences, you’ll also receive the same number of entries into the other, all subject to each Experience’s Entry Limit, which may be found in Section 5 of the applicable Experience Rules. Each entry awarded in connection with this promotion will constitute a single, independent entry in the applicable Experience, will be treated the same as any other entry to the Experience and will have the same chance of winning as any other entry. See the applicable Experience Rules under “Stuff our lawyers want you to read” here: Win a Dream Vacation in an Overwater Villa in the Maldives; Win a Vacation at the Conrad Bora Bora Nui in an Overwater Villa\\n\\n*        *        *\\n\\nFundraising Transparency\\n\\nThis Experience is part of a fundraising campaign for Charities Aid Foundation America (“CAF America”), which is a globally recognized United States 501(c)(3) public charity (Federal Tax ID # 43-1634280). CAF America retains exclusive control over all donations raised in this Experience.\\n\\n(a)        How it works: Omaze and CAF America work together to offer incredible Experiences, like this one. You don’t have to donate to enter, but if you do, 100% of your donation goes to CAF America, who then distributes the donations, minus the Experience fees and costs, to the nonprofit(s) identified on the experience page (the “Designated Grantee(s)”). Our model allows CAF America and the non-profit grantees to spend less time worrying about raising funds and instead focus their energy on doing awesome work.\\n\\n(b)       Where your donation goes: For Omaze Owned Experiences, like this one, 15% of the total donations goes to the Designated Grantee(s) via a grant from CAF America. (If there are multiple Designated Grantees, then this amount is equally distributed to each). CAF America retains a small percentage of the total donations (less than 1%) to cover its own operating costs. Omaze uses the remaining amount to pay for the Experience costs, such as Prize costs, payment processing fees, and advertising to awesome people like you, and to cover our operating costs of providing and maintaining the technology and team that makes this all happen. Owned Experiences have higher costs associated with prizing and promotion, which is why a larger percentage goes to Experience costs.\\n\\n(c)        Designated Grantee Eligibility: Before every Experience, CAF America confirms the Designated Grantee(s) as eligible to receive grants. In the rare case where, after the launch of an Experience but before distribution of the donations, a Designated Grantee fails to maintain eligibility (per CAF America’s grant-making policies and/or applicable laws), then CAF America may (i) withhold distribution of the donations until the Designated Grantee is eligible or (ii) reassign the donations to another nonprofit that supports a similar cause. If CAF America reassigns the donations to an alternate organization, the Experience page will be updated to identify what entity(ies) received the grant(s).\\n\\n(d)        When will the Designated Grantee get the money? Omaze sends 100% of donations from this Experience to CAF America within 2 business days of Omaze’s receipt of the donation. The speed at which CAF America distributes the donations to the Designated Grantee(s) depends on the classification of the Experience and can be anywhere from 2 weeks after Omaze received your donation to 90 days from the close of the Experience. In circumstances where a Designated Grantee fails to maintain eligibility to receive grants, the above grant distribution timeframes may be impacted.\\n\\nFor Experiences where the grant amount is a percentage of total donations (e.g., Premiere and Owned Experiences), CAF America will distribute the donations via multiple grants throughout the duration of the Experience, usually within 10-15 business days following CAF America’s receipt of donations from Omaze.\\n\\nFor Experiences where the grant amount is a percentage of Adjusted Donations (total donations minus Experience costs), CAF America will distribute donations after reconciliation of all Experience costs (usually within 15-90 days following the close of the Experience).\\n\\nCopyright ©2021 Omaze, Inc. All third-party names and trademarks are the property of their respective owners.</ul',
        impact: {
            winDetails:
                'Provide music education and supplies to 113 schools in need.',
            totalAmountRaised: '5000',
        },
        localizations: {
            data: [],
        },
        createdAt: '2022-08-11T20:54:50.860Z',
        updatedAt: '2022-08-12T00:41:17.189Z',
        publishedAt: '2022-08-12T00:41:17.186Z',
        locale: 'en',
    },
};
